[package]
name = "inktex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
egui = "0.18.1"
regex = "1.5.5"
tempfile = "3.3.0"
xcb = {version="1.1.1", features=["debug_atom_names"]}
xcb-util = {version="0.4.0", features=["ewmh"]}
